queue_rules:
  - name: default
    merge_conditions:
      - check-success=Pipelines as Code CI / unit
      - label=staging-ci-complete
    priority_rules:
      - name: rollback
        conditions:
          - label=rollback
        priority: high

pull_request_rules:
  - name: automatic merge of non-staging changes
    conditions:
      - "#approved-reviews-by>=1"
      - "-files~=^.*/(.*/)?staging/.*$"
      - "-label=staging-ci-in-progress"
      - base=master
      - check-success=Pipelines as Code CI / unit
    actions:
      merge:
        method: rebase
  - name: add to merge queue for staging changes in progress
    conditions:
      - "files~=^.*/(.*/)?staging/.*$"
      - label=staging-ci-in-progress
      - "-label=rollback"
      - base=master
      - check-success=Pipelines as Code CI / unit
    actions:
      queue:
        method: merge
        name: default
  - name: prioritized merge for rollback and staging changes
    conditions:
      - "files~=^.*/(.*/)?staging/.*$"
      - label=rollback
      - base=master
      - check-success=Pipelines as Code CI / unit
    actions:
      queue:
        method: merge
        name: default
