queue_rules:
  - name: default
    conditions:
      - label=staging-ci-complete
    actions:
      comment:
        message: "PR added to the merge queue."

pull_request_rules:
  - name: automatic merge of non-staging changes
    conditions:
      - "#approved-reviews-by>=1"
      - "-files~=^.*/(.*/)?staging/.*$"
      - "-label=staging-ci-in-progress"
      - base=master
      - check-success=Pipelines as Code CI / unit
    actions:
      merge:
        method: rebase
        strict: smart
  - name: add to merge queue for staging changes in progress
    conditions:
      - "#approved-reviews-by>=1"
      - "files~=^.*/(.*/)?staging/.*$"
      - label=staging-ci-in-progress
      - base=master
      - check-success=Pipelines as Code CI / unit
    actions:
      queue:
        method: merge
  - name: automatic merge of staging changes
    conditions:
      - "#approved-reviews-by>=1"
      - "files~=^.*/(.*/)?staging/.*$"
      - label=staging-ci-complete
      - "-label=rollback"
      - base=master
      - check-success=Pipelines as Code CI / unit
    actions:
      merge:
        method: rebase
        strict: smart
  - name: prioritized merge for rollback and staging changes
    conditions:
      - "#approved-reviews-by>=1"
      - "files~=^.*/(.*/)?staging/.*$"
      - label=staging-ci-complete
      - label=rollback
      - base=master
      - check-success=Pipelines as Code CI / unit
    actions:
      queue:
        method: merge
        priority: high
