queue_rules:
  - name: default
    merge_conditions:
      - "#approved-reviews-by>=1"
      - check-success=unit
      - label=staging-ci-complete
    priority_rules:
      - name: rollback
        conditions:
          - label=rollback
        priority: high

pull_request_rules:
  - name: automatic merge of rollback
    conditions:
      - check-success=unit
      - "#approved-reviews-by>=1"
      - base=main
      - files~=^[^\/]+\/staging\/?(?:[^\/]+\/?)*$
      - label=staging-ci-in-progress
      - label=rollback
    actions:
      queue:
        method: merge
  - name: automatic merge of staging file change
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - check-success=unit
      - files~=^[^\/]+\/staging\/?(?:[^\/]+\/?)*$
      - label=staging-ci-in-progress
    actions:
      queue:
        method: merge
  - name: automatic merge for other changes not related to staging
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - check-success=unit
    actions:
      merge:
        method: merge
